### ISSUE TITLE
Provide ability to store FACETed results with the facets as dimensions on the metrics

### ISSUE THREAD

**Issue by danifitz** [jsbnr/talisker#3]
Hi,

Consider this query

`select count(*) from (select latest(event) as 'currentState', latest(policyName) as 'policyName', latest(conditionName) as 'conditionName' from NrAiIncident where  priority = 'critical' FACET incidentId, policyId, conditionId, targetName limit max) where currentState='open' FACET currentState,incidentId, policyId, policyName, conditionId, conditionName, targetName since 1 week ago limit max`

And the resulting JSON payload (abbreviated)
```
{
  "results": [
    {
      "count": 0
    },
    {
      "count": 8
    }
  ],
  "metadata": {
    "contents": [
      {
        "function": "alias",
        "alias": "Open P1",
        "contents": {
          "function": "filter",
          "alias": "conditionName LIKE '%P1%'",
          "contents": {
            "function": "count",
            "simple": true
          }
        }
      },
      {
        "function": "alias",
        "alias": "Open non-P1",
        "contents": {
          "function": "filter",
          "alias": "NOT conditionName LIKE '%P1%'",
          "contents": {
            "function": "count",
            "simple": true
          }
        }
      }
    ],
```

I'd like the metric generated to support multiple results for each set of facets.

**Comment by jsbnr** [comment]
This support was added!
